export const ExpoGoogleAuthenticationStatusCodes = {
  LOGIN_CANCELED: "ERR_CANCELED",
  NO_CREDENTIALS: "ERR_NO_CRED",
  NO_PLAY_SERVICES: "ERR_INVALID_ENVIRONMENT",
  BAD_INPUT: "ERR_BAD_INPUT",
  UNKNOWN_ERROR: "ERR_FAIL",
  INVALID_CREDENTIALS: "ERR_CRED",
  LOGOUT_FAILED: "ERR_LOGOUT_FAILED",
  UNSUPPORTED_PLATFORM: "ERR_UNSUPPORTED_PLATFORM",
};
